server:
  port: 7001

eureka:
  instance:
    hostname: eeureka7001.com
  client:
    service-url:
      #单机版: defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群:
      defaultZone: http://eeureka7003.com:7003/eureka/,http://eeureka7002.com:7002/eureka/
    register-with-eureka: false #是否向eureka注册中心注册自己
    fetch-registry: false #false表示自己是注册中心
